version: '3.7'

services:
  data-0:
    image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    container_name: data-0 
    hostname: data-0.iris
    command:
      --key /home/irisowner/license/iris.key
    volumes:
    - ./license:/home/irisowner/license
    - ./misc:/home/irisowner/misc
    - ./UserCPF:/home/irisowner/cpf
    - ./src:/home/irisowner/src
    - ./export:/home/irisowner/export
    - ./data-0:/ISC
    ports:
      - "9092:52773"
      - "9192:1972"
    cap_add:
    - IPC_LOCK
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    - ISC_DATA_DIRECTORY=/ISC/install
  data-1:
    image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    container_name: data-1 
    hostname: data-1.iris
    depends_on:
      - data-0
    command:
      --key /home/irisowner/license/iris.key
    volumes:
    - ./license:/home/irisowner/license
    - ./misc:/home/irisowner/misc
    - ./UserCPF:/home/irisowner/cpf
    - ./data-1:/ISC
    ports:
      - "9093:52773"
      - "9193:1972"
    cap_add:
    - IPC_LOCK
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    - ISC_DATA_DIRECTORY=/ISC/install
  data-2:
    image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    container_name: data-2 
    hostname: data-2.iris
    depends_on:
      - data-0
    command:
      --key /home/irisowner/license/iris.key
    volumes:
    - ./license:/home/irisowner/license
    - ./misc:/home/irisowner/misc
    - ./UserCPF:/home/irisowner/cpf
    - ./data-2:/ISC
    ports:
      - "9094:52773"
      - "9194:1972"
    cap_add:
    - IPC_LOCK
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    - ISC_DATA_DIRECTORY=/ISC/install
  loader:
    init: true
    container_name: loader
    hostname: loader
    build:
      context: ./loader/build
    volumes:
      - ./loader:/app/loader
      - ./export:/app/export

