version: '3.7'

services:
  data-0:
    image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    environment:
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge-pri2021.cpf
  data-1:
    image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    environment:
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge-pri2021.cpf
  data-2:
    image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    environment:
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge-pri2021.cpf
  loader:
    image:
      loader:20211
    build:
      dockerfile: Dockerfile.20211
