apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iris-merge-cpf
data:
  merge.cpf: |-
    [Startup]
    SystemMode=TEST
    WebServer=1
    PasswordHash=FBFE8593AEFA510C27FD184738D6E865A441DE98,u4ocm4qh
    EnableSharding=1

    [config]
    globals=0,0,32,0,0,0
    routines=32
    gmheap=256000 
    MaxServerConn=64
    MaxServers=64

---
apiVersion: v1
kind: Service
metadata:
  name: iris-ext
  labels:
    app: iris
spec:
  type: LoadBalancer
  selector:
    app: iris
  ports:
  - protocol: TCP
    port: 52773
    targetPort: 52773
---

apiVersion: v1
kind: Service
metadata:
  name: iris
  labels:
    app: iris
spec:
  ports:
  - port: 52773
    protocol: TCP
    name: http
  clusterIP: None # Headless Service
  selector:
    app: iris
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data
spec:
  selector:
    matchLabels:
      app: iris
  serviceName: "iris"
  replicas: 3
  template:
    metadata:
      labels:
        app: iris
    spec:
      imagePullSecrets:
        - name: dockerhub-secret      
      terminationGracePeriodSeconds: 10
      containers:
      - args:
        - --key
        - /irissys/key/iris.key
        name: iris
        image: containers.intersystems.com/intersystems/iris:2021.1.0.205.0
        readinessProbe:
          exec:
            command: ["/usr/irissys/dev/Cloud/ICM/waitISC.sh", "iris","1"]
          failureThreshold: 30
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - containerPort: 1972
        - containerPort: 52773
        env:
        - name: ISC_CPF_MERGE_FILE
          value: /irissys/cpf/merge.cpf
        - name: ISC_DATA_DIRECTORY
          value: /iris-mgr/IRIS_conf.d
        - name: TZ
          value: JST-9
        volumeMounts:
        - mountPath: /irissys/cpf/
          name: iris-cpf
        - mountPath: /irissys/key/
          name: iris-key
        - mountPath: /iris-mgr
          name: dbv-mgr
        - mountPath: /vol-data
          name: dbv-data
      volumes:
      - configMap:
          defaultMode: 420
          name: iris-merge-cpf
        name: iris-cpf
      - secret:
          defaultMode: 420
          secretName: iris-key-secret
        name: iris-key
  volumeClaimTemplates:
  - metadata:
      name: dbv-mgr
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: microk8s-hostpath
      #storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: dbv-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: microk8s-hostpath
      #storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi